**ANALISIS PRODUCIÓN ELECTRICA PLACAS SOLARES**
1. Introducción
2. Definición objetivos
3. Indicadores
4. Importación de datos

# 1. Introducción
La instalación de las placas solares en la vivienda ha tenido beneficios significativos en el ahorro energético desde su instalación en septiembre de 2022. 
No obstante en los últimos meses hemos notado un aumento de la factura de la luz. Por este motivo hemos considerado interesante analizar las causas de dicho incremento y más concretamente el estado de la instalación de las placas y su producción eléctrica.

# 2. Objetivo
El objetivo principal del presente estudio es determinar el estado actual de la instalación para decidir si realizar alguna revisión técnica y la posible ampliación de la instalación para mejorar el ahorro energético.

# 3. Indicadores
Los indicadores que nos intereses son:
- Producción eléctrica máxima
- Producción eléctrica media
- Autoconsumo
- Análisis estacional mensual
- Análisis estacional semanal
- Análisis estacional diario

# 4. Importación de datos
Las fuentes de información para el análisis son las facturas eléctricas desde septiembre de 2022 a febrero de 2025, así como la información importada del inversor de las placas, que recoge información horaria desde el día 2024-02-17 04:00:00.
* La información importada del inversor se encuentra en el archivo "inverter_horario.json"

In [4]:
import pandas as pd
df = pd.read_json('inverter_horario.json')
df.tail(1)

     success  ... message
374     True  ...     NaN

[1 rows x 5 columns]

In [13]:
df_plain = pd.json_normalize(df['data'])
df_plain.head(1)

   hasMeter  ... pageSize
0      True  ...       30

[1 rows x 5 columns]

In [20]:
list_with_dict = df_plain['list'].apply(lambda x: [dict(item) for item in x])
list_with_dict.count()

np.int64(375)

In [24]:
list_exploded = list_with_dict.explode()
list_exploded.head()

0    {'inverterPower': 0.0, 'productPower': 0.0, 'o...
0    {'inverterPower': 0.0, 'productPower': 0.0, 'o...
0    {'inverterPower': 0.0, 'productPower': 0.0, 'o...
0    {'inverterPower': 0.0, 'productPower': 0.0, 'o...
0    {'inverterPower': 0.0, 'productPower': 0.0, 'o...
Name: list, dtype: object

In [28]:
df_final = pd.json_normalize(list_exploded)
df_final.head(1)

   inverterPower  productPower  onGridPower    fmtCollectTimeStr  powerProfit
0            0.0           0.0          0.0  2024-02-17 03:00:00          0.0

In [29]:
df_final.to_csv('inverter_horario.csv', index=False)